name: Deploy to GCE

on:
  push:
    branches:
      - main  # Deploy on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ssh-keyscan -H ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to GCE
        env:
          GCE_HOST: ${{ secrets.GCE_HOST }}
          GCE_USER: ${{ secrets.GCE_USER }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $GCE_USER@$GCE_HOST 'bash -s' << 'ENDSSH'
            echo "Starting deployment..."
            cd /home/manankdave1999/Backend/src/
            echo "Current directory: $(pwd)"
            
            # Ensure we're in a git repository
            if [ ! -d .git ]; then
              echo "Error: Not a git repository!"
              exit 1
            fi
            
            # Fetch and reset to origin/main
            git fetch origin
            git reset --hard origin/main
            
            # Install dependencies
            echo "Installing dependencies..."
            npm install
            
            # Restart the server
            echo "Restarting server..."
            pm2 restart server.js
            
            echo "Deployment completed!"
          ENDSSH
