name: Deploy to GCE

on:
  push:
    branches:
      - main  # Deploy on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ssh-keyscan -H ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to GCE
        env:
          GCE_HOST: ${{ secrets.GCE_HOST }}
          GCE_USER: ${{ secrets.GCE_USER }}
          REPO_URL: ${{ secrets.REPO_URL }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $GCE_USER@$GCE_HOST 'bash -s' << 'ENDSSH'
            echo "Starting deployment..."
            
            # Install git if not present
            if ! command -v git &> /dev/null; then
              echo "Git not found. Installing git..."
              sudo apt-get update
              sudo apt-get install -y git
            fi
            
            # Navigate to the project directory
            cd /home/$GCE_USER/Backend/src
            
            # Check if we're in the right directory
            echo "Current directory: $(pwd)"
            
            # Pull the latest changes from the main branch
            git pull origin main
            
            # Install dependencies (from the src directory where package.json is)
            echo "Installing dependencies..."
            npm install
            
            # Restart the server using full path
            echo "Restarting server..."
            pm2 restart /home/$GCE_USER/Backend/src/server.js
            
            echo "Deployment completed!"
          ENDSSH
