name: Deploy to GCE

env:
  DEBUG: true

on:
  push:
    branches:
      - main  # Deploy on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Verify SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << 'EOF'
            # Check Node.js and npm versions
            node -v
            npm -v
          EOF

      - name: Deploy to GCE
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << 'EOF'
            # Navigate to the Backend directory
            cd /home/${{ secrets.GCE_USER }}/Backend

            # Configure git to use deploy token
            git config --global credential.helper store
            echo "https://${{ secrets.TOKEN }}@github.com" > ~/.git-credentials

            # Pull latest changes
            git pull origin main

            # Install dependencies
            npm install

            # Start/Restart the server
            pm2 restart src/server.js

            echo "Deployment completed!"
          EOF

