name: Deploy to GCE

on:
  push:
    branches:
      - main  # Deploy on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ssh-keyscan -H ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to GCE
        env:
          GCE_HOST: ${{ secrets.GCE_HOST }}
          GCE_USER: ${{ secrets.GCE_USER }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $GCE_USER@$GCE_HOST "bash -s '$GCE_USER'" << 'ENDSSH'
            GCE_USER=$1
            echo "Starting deployment..."
            echo "Deploying as user: $GCE_USER"
            
            # Navigate to the src directory
            cd /home/$GCE_USER/Backend
            
            # Pull latest changes
            echo "Pulling latest changes..."
            git pull origin main
            
            # Check if we're in the right directory
            echo "Current directory: $(pwd)"
            
            # Install dependencies
            echo "Installing dependencies..."
            npm install

            cd src
            
            # Start/Restart the server
            echo "Restarting server..."
            if pm2 list | grep -q "server"; then
              pm2 restart server
            else
              pm2 start server.js
            fi
            
            echo "Deployment completed!"
          ENDSSH
