name: Deploy to GCE

on:
  push:
    branches:
      - main  # Deploy on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -H <GCE_PUBLIC_IP> >> ~/.ssh/known_hosts 

      - name: Deploy to GCE
        run: |
          ssh user@<GCE_PUBLIC_IP> << 'EOF'
          /home/manankdave1999/Backend/src/
          git pull origin main
          npm install
          pm2 restart server.js
          EOF

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no user@<GCE_PUBLIC_IP> "echo Connected!"
