name: Deploy to GCE

on:
  push:
    branches:
      - main  # Deploy on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ssh-keyscan -H ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to GCE
        env:
          GCE_HOST: ${{ secrets.GCE_HOST }}
          GCE_USER: ${{ secrets.GCE_USER }}
        run: |
          # First export the username so it's available in the heredoc
          export DEPLOY_USER=$GCE_USER
          
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $GCE_USER@$GCE_HOST << "ENDSSH"
            # Get the username from environment variable
            USER_DIR="/home/${DEPLOY_USER}"
            echo "Deploying to directory: ${USER_DIR}/Backend"
            
            # Navigate to the Backend directory
            cd ${USER_DIR}/Backend

            # Pull latest changes
            git pull origin main

            # Install dependencies
            npm install

            # Navigate to src directory
            cd src

            # Start/Restart the server
            pm2 restart server.js

            echo "Deployment completed!"
          ENDSSH
